version : '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: 'elasticsearch'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - efkVolume:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    container_name: 'kibana'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  fluentd:
    image: fluent/fluentd:v1.16-1
    container_name: 'fluentd1'
    build:
      context: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/log:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    environment:
      - FLUENT_UID=0  # This avoids permission issues

volumes:
  efkVolume: